export const COMMAND_CATALOG = [
  {
    command: 'ls',
    category: 'Navigation',
    purpose: 'List files and directories in the current location.',
    syntax: 'ls',
    example: 'ls',
    output: 'readme.txt  notes/  projects/',
  },
  {
    command: 'cd',
    category: 'Navigation',
    purpose: 'Change the current working directory.',
    syntax: 'cd <directory>',
    example: 'cd notes',
    output: 'The prompt changes to the new path.',
  },
  {
    command: 'pwd',
    category: 'Navigation',
    purpose: 'Print the absolute path of the current directory.',
    syntax: 'pwd',
    example: 'pwd',
    output: '/home/student',
  },
  {
    command: 'mkdir',
    category: 'Files',
    purpose: 'Create a new directory.',
    syntax: 'mkdir <name>',
    example: 'mkdir experiments',
    output: 'A new experiments/ directory appears in ls.',
  },
  {
    command: 'cat',
    category: 'Files',
    purpose: 'Read and print a text file.',
    syntax: 'cat <file>',
    example: 'cat readme.txt',
    output: 'Welcome to LinuxXplore Sandbox.',
  },
  {
    command: 'echo',
    category: 'Files',
    purpose: 'Print text to the terminal.',
    syntax: 'echo <text>',
    example: 'echo hello linux',
    output: 'hello linux',
  },
  {
    command: 'ps',
    category: 'Processes',
    purpose: 'List simulated processes and their states.',
    syntax: 'ps',
    example: 'ps',
    output: 'PID   NAME            STATE',
  },
  {
    command: 'top',
    category: 'Processes',
    purpose: 'Inspect simulated CPU, memory, and virtual-runtime activity.',
    syntax: 'top',
    example: 'top',
    output: 'PID   NAME            STATE       CPU%   MEM(MB)  VRUNTIME',
  },
  {
    command: 'kill',
    category: 'Processes',
    purpose: 'Stop a simulated process by PID.',
    syntax: 'kill <PID>',
    example: 'kill 1001',
    output: 'Process 1001 killed.',
  },
  {
    command: './program &',
    category: 'Processes',
    purpose: 'Launch a simulated program in the background.',
    syntax: './<program> &',
    example: './cpu_intense &',
    output: '[started] cpu_intense',
  },
  {
    command: 'help',
    category: 'Shell',
    purpose: 'Display the complete command help text.',
    syntax: 'help',
    example: 'help',
    output: 'Available commands: ls, cd, pwd, mkdir, cat, ps, top, kill ...',
  },
  {
    command: 'clear',
    category: 'Shell',
    purpose: 'Clear the terminal history.',
    syntax: 'clear',
    example: 'clear',
    output: 'The terminal is empty and ready for the next command.',
  },
]
